<<<<<<< HEAD
import './globals.css'
=======
import '../styles/globals.css'
>>>>>>> 78f8f8a4863a68e25fcccc011a4b61208e8aa7ad
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
<<<<<<< HEAD
  title: 'Create Next App',
  description: 'Generated by create next app',
=======
  title: 'Kohta Blog Site | エンジニアブログ',
  description:
    'こちらのサイトではkohtaのBlogをご覧いただけます。内容はプログラミングの学習内容からテック系のガジェット紹介などがあります。',
>>>>>>> 78f8f8a4863a68e25fcccc011a4b61208e8aa7ad
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
